      
name: 🐛 Bug report
description: Report a bug to help us improve ...
title: "[Bug]: "
labels: [bug] 
body:
  - type: input
    id: gva
    attributes:
      label: 版本
      description: 请输入您当前使用的项目版本?
      placeholder: 2.4.5Beta
    validations:
      required: true
  - type: input
    id: token
    attributes:
      label: token 数目
      description: 请输入悬赏token的数目?
      placeholder: 
      value: "500"
    validations:
      required: true
  - type: input
    id: publicKey
    attributes:
      label: PublicKey
      description: 请输入你的PublicKey
      placeholder: 
    validations:
      required: true
  - type: input
    id: golang
    attributes:
      label: Golang 版本
      description: 请输入您当前使用的GOLANG版本?
      placeholder: go 1.16
    validations:
      required: true
  - type: dropdown
    id: reappearance
    attributes:
      label: 是否依旧存在
      description: 是否可以在master分支复现此bug?
      options:
        - 可以
        - 不可以
        - 未测试
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: bug描述
      description: 请简要描述bug以及复现过程.
      placeholder: |
        1. 首先...
        2. 然后...
    validations:
      required: true
  - type: textarea
    id: advise
    attributes:
      label: 修改建议
      description: 您有好的建议或者修改方案可以提供给我们。

    